In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv("/content/drive/MyDrive/Datasets/(6DM2) Data Tugas.csv")
data

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height
0,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
1,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
2,?,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4
3,164,audi,gas,four,sedan,99.8,176.6,66.2,54.3
4,164,audi,gas,four,sedan,99.4,176.6,66.4,54.3
...,...,...,...,...,...,...,...,...,...
200,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5
201,95,volvo,gas,four,sedan,109.1,188.8,68.8,55.5
202,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5
203,95,volvo,diesel,four,sedan,109.1,188.8,68.9,55.5
204,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5

In [ ]:
#Konversi Nilai Yang Hilang
data.replace(["unknown","?","NaN","nan","NA"], np.nan, inplace=True)
data.isnull().sum()

normalized-losses    41
make                  4
bahan-bakar          13
jumlah-pintu         18
body-style           12
wheel-bases           3
length                8
width                 5
height                4
dtype: int64

In [ ]:
categorical_columns = ['make','bahan-bakar','jumlah-pintu','body-style']
data[categorical_columns] = data[categorical_columns].fillna("unknown")

for col in categorical_columns:
    print("Kategori pada kolom:", col)
    print(data[col].value_counts())
    print("\n")

Kategori pada kolom: make
make
toyota           32
mazda            17
nissan           17
honda            13
mitsubishi       12
volkswagen       12
volvo            11
subaru           11
peugot           11
dodge             9
mercedes-benz     8
bmw               8
plymouth          7
audi              7
saab              6
porsche           4
unknown           4
isuzu             4
alfa-romero       3
chevrolet         3
jaguar            3
renault           2
mercury           1
Name: count, dtype: int64


Kategori pada kolom: bahan-bakar
bahan-bakar
gas        173
diesel      19
unknown     13
Name: count, dtype: int64


Kategori pada kolom: jumlah-pintu
jumlah-pintu
four       101
two         86
unknown     18
Name: count, dtype: int64


Kategori pada kolom: body-style
body-style
sedan          88
hatchback      67
wagon          24
unknown        12
hardtop         8
convertible     6
Name: count, dtype: int64

In [ ]:
mean_length = data['length'].mean()
mean_width = data['width'].mean()
mean_height = data['height'].mean()

data['length'].fillna(mean_length, inplace=True)
data['width'].fillna(mean_width, inplace=True)
data['height'].fillna(mean_height, inplace=True)

/tmp/ipykernel_238/3950940457.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['length'].fillna(mean_length, inplace=True)
/tmp/ipykernel_238/3950940457.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['width'].fillna(mean_width, inplace=True)
/tmp/ipykernel_238/3950940457.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['height'].fillna(mean_height, inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   normalized-losses  164 non-null    object
 1   make               205 non-null    object
 2   bahan-bakar        205 non-null    object
 3   jumlah-pintu       205 non-null    object
 4   body-style         205 non-null    object
 5   wheel-bases        202 non-null    float64
 6   length             205 non-null    float64
 7   width              205 non-null    float64
 8   height             205 non-null    float64
dtypes: float64(4), object(5)
memory usage: 14.5+ KB

In [ ]:
#Min-Max Normalization

min_val = data['wheel-bases'].min()
max_val = data['wheel-bases'].max()

data['wheel-bases-normalized'] = (data['wheel-bases'] - min_val) / (max_val - min_val)
data[['wheel-bases','wheel-bases-normalized']].head()

   wheel-bases  wheel-bases-normalized
0         88.6                0.058309
1         88.6                0.058309
2         94.5                0.230321
3         99.8                0.384840
4         99.4                0.373178

In [ ]:
columns = ['length','width','height']

for col in columns:
    data[col + '_zscore'] = (data[col] - data[col].mean()) / data[col].std()

data[['length_zscore','width_zscore','height_zscore']].head()

   length_zscore  width_zscore  height_zscore
0      -0.428526     -0.867630      -2.038094
1      -0.428526     -0.867630      -2.038094
2      -0.226967     -0.204232      -0.552035
3       0.226541      0.127467       0.232274
4       0.226541      0.222238       0.232274